/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2017-11-18 02:32:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

  request.setAttribute("pageTitle", "Login");
  request.setAttribute("siteName", "Moodle");

      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/jsp/header.jsp", out, false);
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("  <div class=\"card card-register mx-auto mt-5\">\n");
      out.write("    <div class=\"card-header\">Login</div>\n");
      out.write("    <div class=\"card-body\">\n");
      out.write("\n");
      out.write("      <form action=\"https://1-dot-researchmanagement-178603.appspot.com/login\" method=\"post\" name=\"registration\" id=\"registration\">\n");
      out.write("\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("          <div class=\"form-row\">\n");
      out.write("            <div class=\"col-md-12\">\n");
      out.write("              <label for=\"name\">Usuário</label>\n");
      out.write("              <input class=\"form-control\" id=\"user\" name=\"user\" type=\"text\" aria-describedby=\"nameHelp\" placeholder=\"Insira seu nome\" required>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("          <div class=\"form-row\">\n");
      out.write("            <div class=\"col-md-12\">\n");
      out.write("              <label for=\"sobrenome\">Senha</label>\n");
      out.write("              <input class=\"form-control\" type=\"password\" id=\"password\" name=\"password\" aria-describedby=\"nameHelp\" placeholder=\"Insira seu sobrenome\" required>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <input type=\"submit\" class=\"btn btn-success btn-block\" id=\"cadastrar-btn\" value=\"Acessar\" >\n");
      out.write("      </form>\n");
      out.write("\n");
      out.write("      <div class=\"text-center\">\n");
      out.write("        <a class=\"d-block small mt-3\" href=\"register.jsp\">Criar Usuário</a>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("<script src=\"../js/login.js\"></script>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/jsp/footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
